server:  servlet:    context-path: ${context-path}spring:
  datasource:    hikari:
      connectionTimeout: ${DATASOURCE_MAX_LIFETIME:3000}
      minimum-idle: 1
      maximum-pool-size: ${DATASOURCE_MAXIMUM_POOL_SIZE:5}
      idle-timeout: ${DATASOURCE_IDLE_TIMEOUT:5000}
      max-lifetime: ${DATASOURCE_MAX_LIFETIME:1000}
      auto-commit: true
management:
  endpoints:
    enabled-by-default: false
  endpoint:
    health:
      enabled: true       metrics:
      enabled: true
    mappings:      enabled: true 
    info:
      enabled: true
    exposure:      include: \*
      exclude: env,beans
  health:
    db:
      enabled: false
      